# setuptools > 64.0.0 for local editable installations
[build-system]
requires = ["setuptools >= 68.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "FoodFusionAI"
version = "0.0.1"
authors = [
    { name = "Kai Werk", email = "werkkai@hu-berlin.de" },
]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3.10",
]
keywords = [ "Food", "Fusion", "AI"]
#Vercel benötigt 3.12
requires-python = ">=3.12"
dependencies = [
]

# für coverage später
[tool.coverage.run]
omit = [
    #"src/something/we/dont/want/*",
]

# für cli später
[project.scripts]

[project.urls]
"Homepage" = "https://github.com/kwrk1/FoodFusionAI"
"Bug Tracker" = "https://github.com/kwrk1/FoodFusionAI/issues"

[project.optional-dependencies]
dev = [
    "twine",
    "black",
    "pytest>=7.2.2",
    "pytest-cov>=4.1.0",
    "pytest-html>=3.2.0",
]