app:
  title: "FoodFusionAI"
  version: "0.0.1"
  status: "prod"                                              # set to "prod" when launching

api:
  version: "v1"
  description: "Access to the LLM and the user's data"
  allow_origins:
    - "https://zealous-bush-0277f6903.5.azurestaticapps.net/"
  local:                                                      # local for development and testing purposes
    host: "0.0.0.0"
    port: 8000
  hosted:
    url: "https://foodfusion.azurewebsites.net/"

llm:
  model_name: "gemini-1.5-flash"
  max_tokens: 1048576
  temperature: 0.7             

database:
  sql_database:
    server: "foodfusionai"
    database_name: "users"
    username: "adminuser"
  echo: true

logging:
  level: "INFO"