app:
  title: "FoodFusionAI"
  version: "0.0.1"
  status: "dev"                                               # set to "prod" when launching

api:
  version: "v0.0.1"
  description: "Access to the LLM and the user's data"
  local:                                                      # local for development and testing purposes
    host: "0.0.0.0"
    port: 8000
  hosted:
    url: "todo"

llm:
  model_name: "google/flan-t5-base"                           # flan-t5-large, if poor performance
  max_tokens: 512                                             # max input tokens
  temperature: 0.7             

database:
  url: "src/backend/database/todo.db"   
  echo: true                                                  # change to false when launching                   

logging:
  level: "DEBUG"                                                      
  path: "src/backend/logs/logs.log"           